### ISSUE TITLE
第一章 “增加先验” 无法通过单元测试

### ISSUE THREAD

**Issue by ChandlerBBT** [chansonZ/book-ml-sem#4]
书中第27页的代码

    def score(self, email_file):
        if self.total_count[self.CAT[0]] == 0 or self.total_count[self.CAT[1]] == 0:
            self.train()

        result = self.P.copy()
        for ww in EmailClassifier.get_words_from_file(email_file):
            for cc in self.CAT:
                v = self.training[cc][ww]
                p = (v + 1) / (self.total_count[cc] + 1)
                result[cc] *= p

这段代码无法通过单元测试，存在两个问题，

1. AssertionError: None is not an instance of <class 'dict'> : Second argument is not a dictionary
2. AssertionError: {'ham': 0.0034722, 'spam': 0.0019436} != {'ham': 0.003472222222222222, 'spam': 0.0019436345966958213}
- {'ham': 0.0034722, 'spam': 0.0019436}
+ {'ham': 0.003472222222222222, 'spam': 0.0019436345966958213}
?                  +++++++++++                   ++++++++++++

建议修改如下：

    def score(self, email_file):
        if self.total_count[self.CAT[0]] == 0 or self.total_count[self.CAT[1]] == 0:
            self.train()

        result = self.P.copy()
        for ww in EmailClassifier.get_words_from_file(email_file):
            for cc in self.CAT:
                v = self.training[cc][ww]
                p = (v + 1) / (self.total_count[cc] + 1)
                result[cc] *= p
                result[cc] = round(result[cc], 7)
        return result

**Comment by chansonZ** [comment]
你的建议是稳妥的，将小数点限制，增加：

result[cc] = round(result[cc], 7)
