### ISSUE TITLE
第一章勘误2有误

### ISSUE THREAD

**Issue by ChandlerBBT** [chansonZ/book-ml-sem#5]
def judge(score_dict):
    '''二分类'''
    keys = self.CAT #list(score_dict.keys())

应该是  

def judge(score_dict):
    '''二分类'''
    keys = EmailClassifier.CAT

**Comment by ChandlerBBT** [comment]
```python
keys = ['ham', 'spam']
```

**Comment by chansonZ** [comment]
谢谢！ 原意是定义常量，没有较好的实现，直接用了实例引用，可自行修改
