### ISSUE TITLE
第一章 7.预测与验证中的文件路径问题

### ISSUE THREAD

**Issue by ChandlerBBT** [chansonZ/book-ml-sem#6]
s = '../data/processed/spam_400/'
h = '../data/processed/ham_1120/'
clf = EmailClassifier(s, h)
clf.train()

请问这里的s和h的路径是哪里来的？ 我翻了上下文和仓库里的数据包，都没有找到这个文件路径

**Comment by chansonZ** [comment]
谢谢！是遗漏上传了，已在 data.zip 中添加 processed 文件夹的数据
